/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    AMenu: typeof import('antdv-next')['Menu']
    ATabs: typeof import('antdv-next')['Tabs']
    Card: typeof import('./src/components/card.vue')['default']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
  }
}
